### ISSUE TITLE
Files get overwritten if they have the same name

### ISSUE THREAD

**Issue by travelalpaca** [sirjeppe/SVGRepoCollectionDownloader#1]
If a collection has multiple SVGs with the same filename, this python code does not handle that conflict well and you end up with just one file instead of multiple files.  I suggest that there should either be an index added to the output filename so that there can't be duplicates, or some other way to detect when a filename already exists in the destination directory and avoid the name conflict somehow.

I tested one solution by adding an "index=1" variable, then in the for loop changed from:
`file_name = url.rsplit('/', 1)[-1]`
to
`file_name = "{:03d}".format(index)+" "+url.rsplit('/', 1)[-1]`
`index += 1`

This prepends each filename with an index and avoids duplicate filenames in the destination directory.

**Comment by sirjeppe** [comment]
Thanks for the report! Do you have an example of a collection where this is happening?

**Comment by travelalpaca** [comment]
> Thanks for the report! Do you have an example of a collection where this is happening?

https://www.svgrepo.com/collection/space-9/

The above collection has 49 items, but you end up with far fewer because it's full of duplicate names.  For example it has 5 files each named "astronaut", and while some do appear to be actual duplicates, the download results in just 1 "astronaut" file and you'd be missing the variety of SVGs under astronaut.

**Comment by sirjeppe** [comment]
Perfect! Thanks! I'll look into it when I get time! :-)

**Comment by sirjeppe** [comment]
Should be fixed on main now!

**Comment by travelalpaca** [comment]
> Should be fixed on main now!

It is, thank you!
